const frame=document.getElementById('app');
const results=document.getElementById('results');
const key='smriticare-garden-v1';
const backup=localStorage.getItem(key);
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const doc=()=>frame.contentDocument;
const win=()=>frame.contentWindow;
const q=s=>doc().querySelector(s);
const all=s=>[...doc().querySelectorAll(s)];
let passes=0;
function report(label){passes++;results.textContent+=`\nPASS ${passes}: ${label}`;console.log(`PASS ${passes}: ${label}`);}
function assert(condition,label){if(!condition)throw new Error(label);report(label);}
async function wait(fn,label,timeout=25000){const end=Date.now()+timeout;while(Date.now()<end){try{if(fn())return;}catch{}await pause(40);}throw new Error(`Timed out: ${label}`);}
async function click(el){if(!el)throw new Error('Missing clickable control');el.click();await pause(75);}
const find=(text,scope='button,a')=>all(scope).find(el=>el.textContent.trim()===text);
async function button(text){await click(find(text,'button'));}
async function set(el,value){if(!el)throw new Error('Missing form field');const proto=el.tagName==='TEXTAREA'?win().HTMLTextAreaElement.prototype:el.tagName==='SELECT'?win().HTMLSelectElement.prototype:win().HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,value);el.dispatchEvent(new win().Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));await pause(45);}
async function go(path,selector){win().location.hash=path;await pause(120);await wait(()=>q(selector),`${path} ${selector}`);}
async function begin(id){await go(`/app/games/${id}`,'.game-intro');await button('Let’s begin');await wait(()=>!q('.game-intro'),'game started');}
async function close(){if(q('[aria-label="Close dialog"]'))await click(q('[aria-label="Close dialog"]'));await pause(160);}
const state=()=>JSON.parse(localStorage.getItem(key));
async function submit(){const form=q('.modal form')||q('.auth-card form');form.requestSubmit();await pause(150);}
async function quiz(answers){for(let i=0;i<answers.length;i++){await click(all('.quiz-options button')[answers[i]]);await click(q('.quiz-game>.btn'));}await wait(()=>q('.game-result'),'quiz result');}
async function sequence(id){await begin(id);for(const [a,b] of [[0,1],[1,3],[2,3]]){await click(all('.sequence-step')[a]);await click(all('.sequence-step')[b]);}await click(q('.sequence-game>.btn'));await click(q('.sequence-game>.btn'));await wait(()=>q('.game-result'),`${id} result`);}
async function observed(id,roundAnswers){await begin(id);for(let round=0;round<roundAnswers.length;round++){await button('I’m ready');for(const i of roundAnswers[round])await click(all('.object-choices button')[i]);await click(q('.observe-game .wrap-actions>.btn'));await click(q('.observe-game .wrap-actions>.btn'));}await wait(()=>q('.game-result'),`${id} result`);}
async function run(){
 results.textContent='Running real React interactions…';
 await wait(()=>q('.auth-card'),'initial React render',60000);
 const seed=state();seed.session=null;seed.points=0;seed.completed=[];seed.challenges=[];seed.settings={...seed.settings,textSize:1,motion:true,sound:false};localStorage.setItem(key,JSON.stringify(seed));
 frame.contentWindow.location.reload();await pause(300);await wait(()=>q('.auth-card'),'fixture reload',60000);
 await button('Step into SmritiCare');await wait(()=>q('.dashboard-top-grid'),'senior sign-in');assert(state().session==='senior','Demo login opens the senior dashboard');
 await begin('who-is-this');await quiz([0,2,1]);assert(state().points===20&&state().completed.length===1,'Who Is This completion persists one seed and 20 points');assert(!!q('.earned-banner'),'First Step achievement unlocks');
 await click(find('Visit my garden'));await wait(()=>q('.full-garden'),'garden');assert(q('.garden-stats').textContent.includes('20'),'Garden immediately reflects earned journey points');await click(q('[aria-label="Your growing tree"]'));assert(!!q('[role="dialog"]'),'Garden tree opens a detail modal');await close();
 await go('/app/memories','.memory-grid');await click(q('.memory-image-button'));assert(!!q('.memory-detail'),'Memory detail modal opens');const favorites=state().memories.filter(m=>m.favorite).length;await click(q('.memory-detail .wrap-actions .btn:nth-child(2)'));assert(state().memories.filter(m=>m.favorite).length!==favorites,'Favorite action persists');await close();
 await go('/app/family','.family-grid');await click(q('.family-profile-open'));assert(!!q('.family-profile'),'Family profile opens');await click(find('Send a message','button'));await wait(()=>q('.chat-compose'),'chat navigation');await set(q('.chat-compose input'),'A little hello from the automated demo check.');q('.chat-compose').requestSubmit();await pause(100);assert(Object.values(state().messages).flat().some(m=>m.text.includes('automated demo check')),'Sending a message adds it to persistent conversation');
 await click(q('[aria-label="Create a family challenge"]'));await submit();await close();assert(state().challenges.length===1,'Family challenge creation persists');
 await begin('memory-match');const grouped={};all('.match-card').forEach(card=>{const symbol=card.querySelector('.card-front').textContent;(grouped[symbol]??=[]).push(card);});for(const pair of Object.values(grouped)){await click(pair[0]);await click(pair[1]);await pause(370);}await wait(()=>q('.match-complete'),'all pairs matched');await click(q('.match-complete .btn'));assert(state().completed.some(c=>c.game==='memory-match'),'All eight Memory Match pairs complete correctly');assert(q('.earned-banner')?.textContent.includes('Perfect Pair'),'Memory Match unlocks its achievement');
 await sequence('daily-sequence');assert(state().completed.some(c=>c.game==='daily-sequence'),'Daily Sequence tap-to-swap completes');
 await sequence('recipe-steps');assert(state().completed.some(c=>c.game==='recipe-steps'),'Recipe Steps tap-to-swap completes');
 await begin('memory-market');await button('Let’s go to the market');for(const i of [0,2,3,5])await click(all('.market-shelves button')[i]);await click(q('.market-game .wrap-actions>.btn'));await click(q('.market-game .wrap-actions>.btn'));assert(!!q('.game-result'),'Memory Market selection completes');
 await observed('remember-room',[[0,2,3],[0,2,3,5],[0,1,2,3,4,5]]);assert(state().completed.some(c=>c.game==='remember-room'),'Remember the Room completes all three rounds');
 await observed('object-memory',[[1],[0],[4]]);assert(state().completed.some(c=>c.game==='object-memory'),'Object Memory completes progressively larger rounds');
 await begin('family-memory');await quiz([1,0,2]);assert(state().completed.length===8&&state().points===160,'Family Memory includes the created challenge; eight games award exactly 160 points');
 await go('/app/journey','.timeline');assert(q('.timeline').textContent.includes('Family Memory completed'),'Journey timeline includes newly completed activities');
 await go('/app/settings','.settings-grid');await click(q('[aria-label="Increase text size"]'));assert(doc().documentElement.style.fontSize==='17.6px','Accessibility text size changes the actual interface');await click(q('[aria-label="Reduce motion"]'));assert(state().settings.motion===false,'Reduced-motion preference toggles and persists');await click(q('[aria-label="Reduce motion"]'));
 await go('/app/reminders','.reminders-list');await button('Add reminder');await set(q('.modal input:not([type])'),'Water the verification sunflower');await submit();await close();let reminder=state().reminders.find(r=>r.title==='Water the verification sunflower');assert(!!reminder,'Add reminder appears in persistent data');await click(q('[aria-label="Snooze Water the verification sunflower 15 minutes"]'));assert(state().reminders.find(r=>r.id===reminder.id).time!==reminder.time,'Snooze advances the reminder by 15 minutes');await click(q('[aria-label="Edit Water the verification sunflower"]'));await set(q('.modal input:not([type])'),'Water the verification flowers');await submit();await close();assert(state().reminders.some(r=>r.title==='Water the verification flowers'),'Edit reminder saves changes');await click(q('[aria-label="Delete Water the verification flowers"]'));await button('Remove reminder');await close();assert(!state().reminders.some(r=>r.id===reminder.id),'Delete reminder removes only the selected record');
 await go('/app/games/who-is-this','.game-intro');await button('Let’s begin');await click(all('.quiz-options button')[1]);assert(q('.game-feedback')?.classList.contains('gentle'),'Incorrect quiz choices show gentle feedback');await click(q('[aria-label="Restart game"]'));await button('Start again');await close();assert(q('.round-progress').textContent.includes('1 of 3')&&!q('.game-feedback'),'Restart resets game state without changing rewards');await click(find('All activities','button'));await button('Back to games');await close();assert(!!q('.game-grid'),'Game exit confirmation returns to hub');
 await go('/app/home','.dashboard-top-grid');await click(q('.skip-link'));assert(win().location.hash==='#/app/home'&&doc().activeElement.id==='app-main','Skip navigation focuses main content without breaking HashRouter');
 await click(q('[aria-label="Log out"]'));await button('Log out');await close();await wait(()=>q('.auth-card'),'logout');assert(state().session===null,'Logout returns to login and preserves progress');
 await button('For my family');await button('Step into SmritiCare');await wait(()=>q('.family-action-bar'),'family login');assert(state().session==='family','Family demo login opens the family dashboard');await button('Send memory');await set(q('.modal input[maxlength="90"]'),'A family memory from verification');await set(all('.modal input').find(i=>i.placeholder==='Our home'),'Our garden');await set(q('.modal textarea'),'A lovely memory sent from family mode.');await submit();await close();assert(state().memories.some(m=>m.title==='A family memory from verification'&&m.from==='Rahul'),'Family can add a new memory');await click(q('.role-switch'));await wait(()=>win().location.hash==='#/app/home','senior mode');await go('/app/memories','.memory-grid');assert(q('.memory-grid').textContent.includes('A family memory from verification'),'New family memory is visible in senior mode');
 const expected=state().completed.length;win().location.reload();await pause(300);await wait(()=>q('.memory-grid'),'persistent reload',60000);assert(state().completed.length===expected&&q('.memory-grid').textContent.includes('A family memory from verification'),'Progress and shared memories survive a full page reload');
 for(const [path,selector] of [['/app/profile','.profile-card'],['/app/achievements','.achievements-grid'],['/family/journey','.timeline'],['/family/memories','.memory-grid'],['/family/challenges','.family-challenges'],['/app/memories/goa','.memory-route'],['/signup','.auth-card'],['/about','#about'],['/how-it-works','#how-it-works'],['/features','#features'],['/games-preview','#games-preview'],['/family-connection','#family-connection'],['/memory-garden','#memory-garden'],['/accessibility','#accessibility'],['/contact','#contact'],['/',' .hero']]){await go(path,selector);assert(!!q(selector),`Route ${path} renders`);}
 assert(!q('.initial-loading'),'No runtime error boundary appeared during verification');
 results.className='pass';results.textContent+=`\n\nALL ${passes} CHECKS PASSED.`;console.log(`ALL ${passes} CHECKS PASSED`);
}
run().catch(error=>{results.className='fail';results.textContent+=`\nFAIL: ${error.message}`;console.error(`VERIFICATION FAILED: ${error.message}`);}).finally(()=>{frame.remove();if(backup===null)localStorage.removeItem(key);else localStorage.setItem(key,backup);results.id='verification-done';});
