import React, { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import * as Icons from 'lucide-react';
import { useStore } from '../../store/state.jsx';
import { imageFallback } from '../../data/images.js';
export function Icon({name='Leaf',size=20,...props}){const Component=Icons[name]||Icons.Leaf;return <Component size={size} strokeWidth={1.7} aria-hidden="true" {...props}/>;}
export function Button({children,icon,variant='',className='',to,...props}){const content=<>{icon&&<Icon name={icon}/>}<span>{children}</span></>;return to?<Link to={to} className={`btn ${variant} ${className}`} {...props}>{content}</Link>:<button className={`btn ${variant} ${className}`} {...props}>{content}</button>;}
export function Photo({src,alt='',className='',...props}){return <img src={src} alt={alt} className={className} loading="lazy" onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src=imageFallback;}} {...props}/>;}
export function Avatar({src,name,size=''}){return <span className={`avatar ${size}`}>{src?<Photo src={src} alt={name}/>:name?.[0]}</span>;}
export function Logo({light=false}){return <Link to="/" className={`brand ${light?'light':''}`} aria-label="SmritiCare home"><span className="brand-mark"><Icon name="Sprout" size={26}/></span><span>Smriti<span className="brand-care">Care</span><small>GROW A LITTLE, EVERY DAY</small></span></Link>;}
export function PageHeader({eyebrow,title,description,action}){return <header className="page-header"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{action}</header>;}
export function EmptyState({icon='Sprout',title,description,children}){return <div className="empty-state"><Icon name={icon} size={36}/><h3>{title}</h3><p>{description}</p>{children}</div>;}
export function LoadingState(){return <div className="skeleton-grid" aria-label="Loading your next moment" role="status">{[1,2,3].map(n=><div className="skeleton" key={n}/>)}</div>;}
export function Progress({value,label}){return <div className="progress" role="progressbar" aria-label={label} aria-valuenow={value} aria-valuemin="0" aria-valuemax="100"><span style={{width:`${Math.min(100,value)}%`}}/></div>;}
export function ModalHost(){const {modal,setModal}=useStore();const ref=useRef();useEffect(()=>{if(!modal)return;const previous=document.activeElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';const timer=setTimeout(()=>ref.current?.querySelector('button,input,select,textarea,a')?.focus(),60);function keyboard(e){if(e.key==='Escape')setModal(null);if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button:not(:disabled),[href],input,select,textarea,[tabindex="0"]')];if(!nodes.length)return;if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes[nodes.length-1].focus();}else if(!e.shiftKey&&document.activeElement===nodes[nodes.length-1]){e.preventDefault();nodes[0].focus();}}}document.addEventListener('keydown',keyboard);return()=>{clearTimeout(timer);document.body.style.overflow=old;document.removeEventListener('keydown',keyboard);previous?.focus();};},[modal]);return <AnimatePresence>{modal&&<motion.div className="modal-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={e=>{if(e.target===e.currentTarget)setModal(null);}}><motion.section ref={ref} className={`modal ${modal.wide?'wide':''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title" initial={{y:20,scale:.98}} animate={{y:0,scale:1}} exit={{y:10,opacity:0}}><header className="modal-header"><h2 id="modal-title">{modal.title}</h2><button className="icon-btn" aria-label="Close dialog" onClick={()=>setModal(null)}><Icon name="X"/></button></header>{modal.content}</motion.section></motion.div>}</AnimatePresence>;}
export function ToastHost(){const{toasts,setToasts}=useStore();return <div className="toast-stack" role="status" aria-live="polite"><AnimatePresence>{toasts.map(t=><motion.div key={t.id} className="toast" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,x:20}}><span>{t.icon}</span><p>{t.text}</p><button className="icon-btn" aria-label="Dismiss notification" onClick={()=>setToasts(ts=>ts.filter(x=>x.id!==t.id))}><Icon name="X" size={16}/></button></motion.div>)}</AnimatePresence></div>;}
export function Toggle({label,description,checked,onChange}){return <div className="setting-row"><div><strong>{label}</strong>{description&&<p className="muted small">{description}</p>}</div><button role="switch" aria-checked={!!checked} aria-label={label} className={`toggle ${checked?'on':''}`} onClick={()=>onChange(!checked)}><span/></button></div>;}
export function AccessibilityPanel(){const{data,update}=useStore();const s=data.settings;const set=(patch)=>update(d=>({...d,settings:{...d.settings,...patch}}));return <div className="accessibility-panel"><p className="muted">Make this little space feel right for you.</p><div className="setting-row"><div><strong>Text size</strong><p className="small muted">{Math.round(s.textSize*100)}% · A comfortable read</p></div><div className="button-group"><button className="icon-btn bordered" aria-label="Decrease text size" disabled={s.textSize<=.9} onClick={()=>set({textSize:Math.max(.9,+(s.textSize-.1).toFixed(1))})}>A−</button><button className="icon-btn bordered" aria-label="Increase text size" disabled={s.textSize>=1.4} onClick={()=>set({textSize:Math.min(1.4,+(s.textSize+.1).toFixed(1))})}>A+</button></div></div><Toggle label="High contrast" description="Stronger colors and clearer edges" checked={s.contrast} onChange={contrast=>set({contrast})}/><Toggle label="Reduce motion" description="A quieter, more still experience" checked={s.motion} onChange={motion=>set({motion})}/><Toggle label="Sound" description="Gentle tones when you finish an activity" checked={s.sound} onChange={sound=>set({sound})}/><p className="small note"><Icon name="Check" size={16}/> Your preferences are saved on this device.</p></div>;}
export function AccessibilityButton({compact=false}){const{setModal}=useStore();return <button className={compact?'icon-btn':'accessibility-link'} title="Accessibility" aria-label="Accessibility settings" onClick={()=>setModal({title:'Your comfort comes first',content:<AccessibilityPanel/>})}><Icon name="Accessibility"/>{!compact&&<span>Accessibility</span>}</button>;}
export function VoiceAssistant(){const [listening,setListening]=useState(false);const navigate=useNavigate();const{notify}=useStore();useEffect(()=>{if(!listening)return;const timer=setTimeout(()=>{setListening(false);notify('Demo voice command: “Play today’s memory game.”','🎙️');navigate('/app/games/who-is-this');},3400);return()=>clearTimeout(timer);},[listening]);return <div className="voice-assistant">{listening&&<div className="voice-bubble"><small>VOICE DEMO · NO MICROPHONE</small><h3>I'm listening…</h3><div className="waveform">{[1,2,3,4,5,6,7].map(n=><i key={n} style={{animationDelay:`${n*.12}s`}}/>)}</div><p>“Play today's memory game.”</p><button className="text-link" onClick={()=>setListening(false)}>Cancel</button></div>}<button aria-label={listening?'Cancel voice demo':'Open voice assistant demo'} className={`voice-btn ${listening?'active':''}`} onClick={()=>setListening(!listening)}><Icon name={listening?'X':'Mic'} size={22}/></button></div>;}
export function Carousel({items,renderItem,label='Memories'}){const [index,setIndex]=useState(0);const start=useRef(0);const next=()=>setIndex(i=>(i+1)%items.length),prev=()=>setIndex(i=>(i-1+items.length)%items.length);if(!items.length)return null;const visible=[0,1,2].slice(0,items.length).map(n=>items[(index+n)%items.length]);return <section className="carousel" aria-label={label} aria-roledescription="carousel" tabIndex="0" onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();next();}if(e.key==='ArrowLeft'){e.preventDefault();prev();}}} onTouchStart={e=>start.current=e.touches[0].clientX} onTouchEnd={e=>{const diff=start.current-e.changedTouches[0].clientX;if(diff>50)next();else if(diff< -50)prev();}}><div className="carousel-track">{visible.map((item,i)=><div className={`carousel-slide slide-${i}`} key={item.id}>{renderItem(item)}</div>)}</div><div className="carousel-controls"><button className="icon-btn bordered" onClick={prev} aria-label={`Previous ${label}`}><Icon name="ArrowLeft" size={18}/></button><div className="dots">{items.map((item,i)=><button key={item.id} aria-label={`Go to item ${i+1}`} aria-current={index===i} className={index===i?'active':''} onClick={()=>setIndex(i)}/>)}</div><button className="icon-btn bordered" onClick={next} aria-label={`Next ${label}`}><Icon name="ArrowRight" size={18}/></button></div></section>;}
export function Confirm({text,onConfirm,label='Confirm'}){const{setModal}=useStore();return <><p>{text}</p><div className="modal-actions"><Button variant="secondary" onClick={()=>setModal(null)}>Keep it</Button><Button onClick={()=>{onConfirm();setModal(null);}}>{label}</Button></div></>;}
export class ErrorBoundary extends React.Component{constructor(props){super(props);this.state={error:false};}static getDerivedStateFromError(){return{error:true};}render(){return this.state.error?<main className="initial-loading"><span>🌿</span><h2>Something didn’t go as planned.</h2><p>Your saved moments are still on this device.</p><Button onClick={()=>location.reload()}>Try again</Button></main>:this.props.children;}}
